// Exercise 1: Create a Spring Web Project using Maven

// Steps:
// 1. Go to https://start.spring.io/
// 2. Group: "com.cognizant", Artifact: "spring-learn"
// 3. Add dependencies: Spring Boot DevTools, Spring Web
// 4. Download, extract and import into Eclipse

// ---- File: pom.xml (auto-generated by Spring Initializr) ----
// Key dependencies: spring-boot-starter-web, spring-boot-devtools

// ---- File: src/main/java/com/cognizant/springlearn/SpringLearnApplication.java ----

package com.cognizant.springlearn;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpringLearnApplication {

    private static final Logger LOGGER = LoggerFactory.getLogger(SpringLearnApplication.class);

    public static void main(String[] args) {
        SpringApplication.run(SpringLearnApplication.class, args);
        LOGGER.info("Inside main");
    }
}

// Project Structure:
// src/main/java       - Application code
// src/main/resources  - Application configuration
// src/test/java       - Test code

// @SpringBootApplication combines:
// @Configuration - Marks class as source of bean definitions
// @EnableAutoConfiguration - Enables Spring Boot auto-configuration
// @ComponentScan - Scans for components in current package and sub-packages
